print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/lucien/Documents/Works/Unity/Time/Assets/models/prop.mb"`)
{		
	file -o "/Users/lucien/Documents/Works/Unity/Time/Assets/models/prop.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/lucien/Documents/Works/Unity/Time/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/lucien/Documents/Works/Unity/Time/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/lucien/Documents/Works/Unity/Time/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
